apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-apps
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs-apps
  template:
    metadata:
      labels:
        app: nodejs-apps
    spec:
      containers:
        - name: nodeapp-pod1
          image: node:latest
          ports:
            - name: http
              containerPort: 3001
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 256Mi
        - name: nodeapp-pod2
          image: node:latest
          ports:
            - name: http
              containerPort: 3002
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 256Mi
