apiVersion: v1
kind: Service
metadata:
  name: nodeapp-service
spec:
  selector:
    app: nodeapp
  type: LoadBalancer
  ports:
    - name: nodeapp-pod1
      port: 3001
      targetPort: 3001
      protocol: TCP
      nodePort: 3001
    - name: nodeapp-pod2
      port: 3002
      targetPort: 3002
      protocol: TCP
      nodePort: 3002
