FROM node:latest

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
COPY package.json ./

RUN npm install

# Bundle app source
COPY . .

EXPOSE 3002
CMD [ "node", "app.js" ]


# docker build -t nicolas/pod2 .
# docker images
# docker run -p 3002:3002 -d nicolas/pod2
# docker ps
# docker rm -f 'container id'

# docker tag nicolas/pod2:latest raydor/pod2
# docker push raydor/pod2

