FROM node:latest

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
COPY package.json ./

RUN npm install

# Bundle app source
COPY . .

EXPOSE 3001
CMD [ "node", "app.js" ]


# docker build -t nicolas/pod1 .
# docker images
# docker run -p 3001:3001 -d nicolas/pod1
# docker ps
# docker rm -f 'container id'

# docker login
# docker push nicolas/app1:latest
